kind: Deployment
apiVersion: apps/v1
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: jmgdemo.azurecr.us/website/website:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: website
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: website
