name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup
      run: echo "VERSION=$(($(date +%s)/60))" >> $GITHUB_ENV
    
    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push
      run: |
          docker build . --file dockerfile --tag ${{ secrets.ACR }}/website/website:${{ env.VERSION }}
          docker push ${{ secrets.ACR }}/website/website:${{ env.VERSION }}
